export const GET_FEEDBACKS_START = 'GET_FEEDBACKS_START';
export const GET_FEEDBACKS_SUCCESS = 'GET_FEEDBACKS_SUCCESS';
export const GET_FEEDBACKS_FAIL = 'GET_FEEDBACKS_FAIL';

export const DELETE_FEEDBACK_START = 'DELETE_FEEDBACK_START';
export const DELETE_FEEDBACK_SUCCESS = 'DELETE_FEEDBACK_SUCCESS';
export const DELETE_FEEDBACK_FAIL = 'DELETE_FEEDBACK_FAIL';

export const ADD_FEEDBACK_START = 'ADD_FEEDBACK_START';
export const ADD_FEEDBACK_SUCCESS = 'ADD_FEEDBACK_SUCCESS';
export const ADD_FEEDBACK_FAIL = 'ADD_FEEDBACK_FAIL';

export const EDIT_FEEDBACK_START = 'EDIT_FEEDBACK_START';
export const EDIT_FEEDBACK_SUCCESS = 'EDIT_FEEDBACK_SUCCESS';
export const EDIT_FEEDBACK_FAIL = 'EDIT_FEEDBACK_FAIL';

export const ADD_COMMENT_TO_FEEDBACK_START = 'ADD_COMMENT_TO_FEEDBACK_START';
export const ADD_COMMENT_TO_FEEDBACK_SUCCESS = 'ADD_COMMENT_TO_FEEDBACK_SUCCESS';
export const ADD_COMMENT_TO_FEEDBACK_FAIL = 'ADD_COMMENT_TO_FEEDBACK_FAIL';